<?php

class flagsWcu extends moduleWcu {

	public $dbPrefix = 'wcu_currencies';
	public $flagPath;
	public $flagExtension;
	public $currencyModule;
	public $optionsPro;

	public function init() {
		parent::init();
		$this->flagPath = $this->getModPath().'img/32/';
		$this->flagExtension = '.png';
		$this->optionsPro = frameWcu::_()->getModule('options_pro')->getModel()->getOptionsPro();

		dispatcherWcu::addAction('flagsList', array($this->getView(), 'getFlagsList'), 10, 2);
		dispatcherWcu::addAction('wcuFlagsSetting', array($this->getView(), 'getFlagsSetting'), 10, 2);
		frameWcu::_()->addStyle('dd', $this->getModPath() . 'css/dd.css');
		frameWcu::_()->addScript('jquery.dd.min', $this->getModPath() . 'js/jquery.dd.min.js', array('jquery'));
	}

	public function getFlagsList() {
	 	$defFlagList = array(
			'EUR' => $this->flagPath . 'EUR' . $this->flagExtension,
			'USD' => $this->flagPath . 'USD' . $this->flagExtension,
			'GBP' => $this->flagPath . 'GBP' . $this->flagExtension,
			'JPY' => $this->flagPath . 'JPY' . $this->flagExtension,
			'INR' => $this->flagPath . 'INR' . $this->flagExtension,
			'UAH' => $this->flagPath . 'UAH' . $this->flagExtension,
			'RUB' => $this->flagPath . 'RUB' . $this->flagExtension,
			'AUD' => $this->flagPath . 'AUD' . $this->flagExtension,
			'AED' => $this->flagPath . 'AED' . $this->flagExtension,
			'AFN' => $this->flagPath . 'AFN' . $this->flagExtension,
			'ALL' => $this->flagPath . 'ALL' . $this->flagExtension,
			'AMD' => $this->flagPath . 'AMD' . $this->flagExtension,
			'ANG' => $this->flagPath . 'ANG' . $this->flagExtension,
			'AOA' => $this->flagPath . 'AOA' . $this->flagExtension,
			'AWG' => $this->flagPath . 'AWG' . $this->flagExtension,
			'AZN' => $this->flagPath . 'AZN' . $this->flagExtension,
			'BAM' => $this->flagPath . 'BAM' . $this->flagExtension,
			'BDT' => $this->flagPath . 'BDT' . $this->flagExtension,
			'BGN' => $this->flagPath . 'BGN' . $this->flagExtension,
			'BHD' => $this->flagPath . 'BHD' . $this->flagExtension,
			'BIF' => $this->flagPath . 'BIF' . $this->flagExtension,
			'BOB' => $this->flagPath . 'BOB' . $this->flagExtension,
			'BTC' => $this->flagPath .'BTC'. $this->flagExtension,
			'BTN' => $this->flagPath .'BTN'. $this->flagExtension,
			'BRL' => $this->flagPath .'BRL'. $this->flagExtension,
			'BWP' => $this->flagPath .'BWP'. $this->flagExtension,
			'BYR' => $this->flagPath .'BYR'. $this->flagExtension,
			'CAD' => $this->flagPath .'CAD'. $this->flagExtension,
			'CDF' => $this->flagPath .'CDF'. $this->flagExtension,
			'CHF' => $this->flagPath .'CHF'. $this->flagExtension,
			'CNY' => $this->flagPath .'CNY'. $this->flagExtension,
			'CRC' => $this->flagPath .'CRC'. $this->flagExtension,
			'CZK' => $this->flagPath .'CZK'. $this->flagExtension,
			'CFP' => $this->flagPath .'CFP'. $this->flagExtension,
			'COP' => $this->flagPath .'COP'. $this->flagExtension,
			'DJF' => $this->flagPath .'DJF'. $this->flagExtension,
			'DKK' => $this->flagPath .'DKK'. $this->flagExtension,
			'DOP' => $this->flagPath .'DOP'. $this->flagExtension,
			'DZD' => $this->flagPath .'DZD'. $this->flagExtension,
			'EGP' => $this->flagPath .'EGP'. $this->flagExtension,
			'ERN' => $this->flagPath .'ERN'. $this->flagExtension,
			'ETB' => $this->flagPath .'ETB'. $this->flagExtension,
			'ETH' => $this->flagPath .'ETH'. $this->flagExtension,
			'ETC' => $this->flagPath .'ETC'. $this->flagExtension,
			'FKP' => $this->flagPath .'FKP'. $this->flagExtension,
			'FJD' => $this->flagPath .'FKP'. $this->flagExtension,
			'GEL' => $this->flagPath .'GEL'. $this->flagExtension,
			'GGP' => $this->flagPath .'GGP'. $this->flagExtension,
			'GHS' => $this->flagPath .'GHS'. $this->flagExtension,
			'GIP' => $this->flagPath .'GIP'. $this->flagExtension,
			'GMD' => $this->flagPath .'GMD'. $this->flagExtension,
			'GNF' => $this->flagPath .'GNF'. $this->flagExtension,
			'GTQ' => $this->flagPath .'GTQ'. $this->flagExtension,
			'HNL' => $this->flagPath .'HNL'. $this->flagExtension,
			'HRK' => $this->flagPath .'HRK'. $this->flagExtension,
			'HTG' => $this->flagPath .'HTG'. $this->flagExtension,
			'HUF' => $this->flagPath .'HUF'. $this->flagExtension,
			'HKD' => $this->flagPath .'HKD'. $this->flagExtension,
			'IDR' => $this->flagPath .'IDR'. $this->flagExtension,
			'ILS' => $this->flagPath .'ILS'. $this->flagExtension,
			'IMP' => $this->flagPath .'IMP'. $this->flagExtension,
			'IQD' => $this->flagPath .'IQD'. $this->flagExtension,
			'IRR' => $this->flagPath .'IRR'. $this->flagExtension,
			'ISK' => $this->flagPath .'ISK'. $this->flagExtension,
			'JEP' => $this->flagPath .'JEP'. $this->flagExtension,
		    'JMD' => $this->flagPath .'JMD'. $this->flagExtension,
			'JOD' => $this->flagPath .'JOD'. $this->flagExtension,
			'KES' => $this->flagPath .'KES'. $this->flagExtension,
			'KGS' => $this->flagPath .'KGS'. $this->flagExtension,
			'KHR' => $this->flagPath .'KHR'. $this->flagExtension,
			'KMF' => $this->flagPath .'KMF'. $this->flagExtension,
			'KPW' => $this->flagPath .'KPW'. $this->flagExtension,
			'KRW' => $this->flagPath .'KRW'. $this->flagExtension,
			'KWD' => $this->flagPath .'KWD'. $this->flagExtension,
			'KZT' => $this->flagPath .'KZT'. $this->flagExtension,
			'LAK' => $this->flagPath .'LAK'. $this->flagExtension,
			'LBP' => $this->flagPath .'LBP'. $this->flagExtension,
			'LKR' => $this->flagPath .'LKR'. $this->flagExtension,
			'LSL' => $this->flagPath .'LSL'. $this->flagExtension,
			'LYD' => $this->flagPath .'LYD'. $this->flagExtension,
			'MAD' => $this->flagPath .'MAD'. $this->flagExtension,
			'MDL' => $this->flagPath .'MDL'. $this->flagExtension,
			'MGA' => $this->flagPath .'MGA'. $this->flagExtension,
			'MKD' => $this->flagPath .'MKD'. $this->flagExtension,
			'MMK' => $this->flagPath .'MMK'. $this->flagExtension,
			'MNT' => $this->flagPath .'MNT'. $this->flagExtension,
			'MOP' => $this->flagPath .'MOP'. $this->flagExtension,
			'MRO' => $this->flagPath .'MRO'. $this->flagExtension,
			'MUR' => $this->flagPath .'MUR'. $this->flagExtension,
			'MVR' => $this->flagPath .'MVR'. $this->flagExtension,
			'MWK' => $this->flagPath .'MWK'. $this->flagExtension,
			'MYR' => $this->flagPath .'MYR'. $this->flagExtension,
			'MZN' => $this->flagPath .'MZN'. $this->flagExtension,
			'MXN' => $this->flagPath .'MXN'. $this->flagExtension,
			'NGN' => $this->flagPath .'NGN'. $this->flagExtension,
			'NIO' => $this->flagPath .'NIO'. $this->flagExtension,
			'NOK' => $this->flagPath .'NOK'. $this->flagExtension,
			'NPR' => $this->flagPath .'NPR'. $this->flagExtension,
			'NZD' => $this->flagPath .'NZD'. $this->flagExtension,
			'OMR' => $this->flagPath .'OMR'. $this->flagExtension,
			'PAB' => $this->flagPath .'PAB'. $this->flagExtension,
			'PEN' => $this->flagPath .'PEN'. $this->flagExtension,
			'PGK' => $this->flagPath .'PGK'. $this->flagExtension,
			'PHP' => $this->flagPath .'PHP'. $this->flagExtension,
			'PKR' => $this->flagPath .'PKR'. $this->flagExtension,
			'PLN' => $this->flagPath .'PLN'. $this->flagExtension,
			'PRB' => $this->flagPath .'PRB'. $this->flagExtension,
			'PYG' => $this->flagPath .'PYG'. $this->flagExtension,
			'QAR' => $this->flagPath .'QAR'. $this->flagExtension,
			'RON' => $this->flagPath .'RON'. $this->flagExtension,
			'RSD' => $this->flagPath .'RSD'. $this->flagExtension,
			'RWF' => $this->flagPath .'RWF'. $this->flagExtension,
			'SAR' => $this->flagPath .'SAR'. $this->flagExtension,
			'SCR' => $this->flagPath .'SCR'. $this->flagExtension,
			'SDG' => $this->flagPath .'SDG'. $this->flagExtension,
			'SGD' => $this->flagPath .'SGD'. $this->flagExtension,
			'SEK' => $this->flagPath .'SEK'. $this->flagExtension,
			'SHP' => $this->flagPath .'SHP'. $this->flagExtension,
			'SLL' => $this->flagPath .'SLL'. $this->flagExtension,
			'SOS' => $this->flagPath .'SOS'. $this->flagExtension,
			'SSP' => $this->flagPath .'SSP'. $this->flagExtension,
			'STD' => $this->flagPath .'STD'. $this->flagExtension,
			'SVC' => $this->flagPath .'SVC'. $this->flagExtension,
			'SYP' => $this->flagPath .'SYP'. $this->flagExtension,
			'SZL' => $this->flagPath .'SZL'. $this->flagExtension,
			'THB' => $this->flagPath .'THB'. $this->flagExtension,
			'TJS' => $this->flagPath .'TJS'. $this->flagExtension,
			'TMT' => $this->flagPath .'TMT'. $this->flagExtension,
			'TND' => $this->flagPath .'TND'. $this->flagExtension,
			'TTD' => $this->flagPath .'TTD'. $this->flagExtension,
			'TOP' => $this->flagPath .'TOP'. $this->flagExtension,
			'TRY' => $this->flagPath .'TRY'. $this->flagExtension,
			'TWD' => $this->flagPath .'TWD'. $this->flagExtension,
			'TZS' => $this->flagPath .'TZS'. $this->flagExtension,
			'UGX' => $this->flagPath .'UGX'. $this->flagExtension,
			'UZS' => $this->flagPath .'UZS'. $this->flagExtension,
			'VEF' => $this->flagPath .'VEF'. $this->flagExtension,
			'VND' => $this->flagPath .'VND'. $this->flagExtension,
			'VUV' => $this->flagPath .'VUV'. $this->flagExtension,
			'WST' => $this->flagPath .'WST'. $this->flagExtension,
			'XAF' => $this->flagPath .'XAF'. $this->flagExtension,
			'XOF' => $this->flagPath .'XOF'. $this->flagExtension,
			'XPF' => $this->flagPath .'XPF'. $this->flagExtension,
			'YER' => $this->flagPath .'YER'. $this->flagExtension,
			'ZAR' => $this->flagPath .'ZAR'. $this->flagExtension,
			'ZMW' => $this->flagPath .'ZMW'. $this->flagExtension,
			'LTC' => $this->flagPath .'LTC'. $this->flagExtension,
			'ZEC' => $this->flagPath .'ZEC'. $this->flagExtension,
			'DASH' => $this->flagPath .'DASH'. $this->flagExtension,
			'XRP' => $this->flagPath .'XRP'. $this->flagExtension,
			'XMR' => $this->flagPath .'XMR'. $this->flagExtension,
			'BCH' => $this->flagPath .'BCH'. $this->flagExtension,
			'NEO' => $this->flagPath .'NEO'. $this->flagExtension,
			'ADA' => $this->flagPath .'ADA'. $this->flagExtension,
			'EOS' => $this->flagPath .'EOS'. $this->flagExtension,
			'UYU' => $this->flagPath .'UYU'. $this->flagExtension,
			'CLP' => $this->flagPath .'CLP'. $this->flagExtension,
			'ARS' => $this->flagPath .'ARS'. $this->flagExtension,
		);
		$customFlagList = isset($this->optionsPro['flags']) ? $this->optionsPro['flags'] : array();
		$flagList = array_merge($customFlagList, $defFlagList);
		return $flagList;
	}

}
